# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tata_kelola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifikasi_pemeliharaan_alternatif_sistem', models.TextField()),
                ('realisasi_software_aplikasi', models.TextField()),
                ('realisasi_inrastruktur_teknologi', models.TextField()),
                ('realisasi_pengelolaan_data', models.TextField()),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata_kelola.Proyek')),
            ],
        ),
    ]
