# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tata_kelola', '0002_step3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manajemen_tingkat_layanan', models.TextField()),
                ('keamanan_keberlangsungan_sistem', models.TextField()),
                ('manajemen_software_aplikasi', models.TextField()),
                ('manajemen_infratruktur', models.TextField()),
                ('manajemen_data', models.TextField()),
                ('manajemen_pihak_ketiga', models.TextField()),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata_kelola.Proyek')),
            ],
        ),
        migrations.CreateModel(
            name='Step5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemeliharaan_software_aplikasi', models.TextField()),
                ('pemeliharaan_infrastruktur_teknologi', models.TextField()),
                ('pemeliharaan_data', models.TextField()),
                ('siklus_hidup_likuidasi_sdit', models.TextField()),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tata_kelola.Proyek')),
            ],
        ),
    ]
