# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 15:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment_filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_comments', to='django_comments.Comment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
